# Generated by Django 2.2.5 on 2019-10-11 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rutas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0003_auto_20191011_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zona_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AddField(
            model_name='zona',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zona_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='modificado por'),
        ),
        migrations.AddField(
            model_name='zona',
            name='rutas',
            field=models.ManyToManyField(related_name='zona_ruta', to='rutas.Ruta'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='clientes',
            field=models.ManyToManyField(related_name='ruta_cliente', to='clientes.Cliente'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ruta_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ruta_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='modificado por'),
        ),
    ]
