# Generated by Django 2.2.5 on 2019-10-17 01:45

import aplicacion.utilidades.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='registro activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('ip_creacion', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip de creación')),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='fecha de modificación')),
                ('ip_modificacion', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip de modificación')),
                ('tipo_identificacion', models.CharField(blank=True, choices=[('CC', 'CEDULA DE CIUDADANIA'), ('TI', 'TARJETA DE IDENTIDAD'), ('CE', 'CEDULA EXTRANJERA'), ('PS', 'PASAPORTE')], max_length=2, null=True, verbose_name='tipo de identificación')),
                ('numero_identificacion', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[aplicacion.utilidades.models.validar_cadenas_numericas], verbose_name='numero de identificación')),
                ('nombres', models.CharField(blank=True, max_length=30, null=True, verbose_name='nombres')),
                ('apellidos', models.CharField(blank=True, max_length=30, null=True, verbose_name='apellidos')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('celular', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='El numero celular debe ingresarse con el formato:\n                                       +573152340969. Máximo 10 digitos', regex='\\+?2?\\d{10}$')], verbose_name='celular')),
                ('direccion', models.CharField(blank=True, max_length=30, null=True, verbose_name='dirección')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
