# Generated by Django 2.2.5 on 2019-09-22 22:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='registro activo')),
                ('eliminado', models.BooleanField(default=False, verbose_name='registro eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('ip_creacion', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip de creación')),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='fecha de modificación')),
                ('ip_modificacion', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip de modificación')),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True, verbose_name='fecha de eliminación')),
                ('ip_eliminacion', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip de eliminación')),
                ('tipo_identificacion', models.CharField(blank=True, choices=[('CC', 'CEDULA DE CIUDADANIA'), ('TI', 'TARJETA DE IDENTIDAD'), ('CE', 'CEDULA EXTRANJERA'), ('PS', 'PASAPORTE')], max_length=2, null=True, verbose_name='tipo de identificación')),
                ('numero_identificacion', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='numero de identificación')),
                ('nombres', models.CharField(blank=True, max_length=30, null=True, verbose_name='nombres')),
                ('apellidos', models.CharField(blank=True, max_length=30, null=True, verbose_name='apellidos')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('celular', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='El numero celular debe ingresarse con el formato:\n                                       +573152340969. Máximo 10 digitos', regex='\\+?2?\\d{10}$')], verbose_name='celular')),
                ('direccion', models.CharField(blank=True, max_length=30, null=True, verbose_name='dirección')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_eliminado_por', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
