# Generated by Django 2.2.5 on 2019-10-11 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geolocalizacion', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='barrio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geolocalizacion.Barrio', verbose_name='barrio'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geolocalizacion.Ciudad', verbose_name='ciudad'),
        ),
    ]
