# Generated by Django 2.2.5 on 2019-09-22 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='eliminado_por',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_eliminacion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='ip_eliminacion',
        ),
    ]
