# Generated by Django 2.2.5 on 2019-10-11 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodega', '0002_auto_20191011_0225'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facturacion', '0001_initial'),
        ('clientes', '0003_auto_20191011_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoventa',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productoventa_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AddField(
            model_name='productoventa',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producto_venta_factura', to='facturacion.Factura', verbose_name='factura'),
        ),
        migrations.AddField(
            model_name='productoventa',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productoventa_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='modificado por'),
        ),
        migrations.AddField(
            model_name='productoventa',
            name='producto_detallado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producto_venta_producto_detallado', to='bodega.ProductoDetallado', verbose_name='producto detallado'),
        ),
        migrations.AddField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.Cliente', verbose_name='cliente'),
        ),
        migrations.AddField(
            model_name='factura',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factura_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AddField(
            model_name='factura',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factura_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='modificado por'),
        ),
        migrations.AddField(
            model_name='abonocredito',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abonocredito_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AddField(
            model_name='abonocredito',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abono_factura_factura', to='facturacion.Factura', verbose_name='factura'),
        ),
        migrations.AddField(
            model_name='abonocredito',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abonocredito_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='modificado por'),
        ),
        migrations.CreateModel(
            name='FacturaCredito',
            fields=[
            ],
            options={
                'verbose_name': 'Credito',
                'verbose_name_plural': 'Creditos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('facturacion.factura',),
        ),
    ]
