# Generated by Django 2.2.5 on 2019-10-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_auto_20191011_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonocredito',
            name='valor_abono',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='valor del abono'),
        ),
        migrations.AlterField(
            model_name='productoventa',
            name='precio_venta',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='precio de venta'),
        ),
        migrations.AlterField(
            model_name='productoventa',
            name='unidades_vendidas',
            field=models.PositiveIntegerField(verbose_name='unidades vendidas'),
        ),
        migrations.AlterField(
            model_name='productoventa',
            name='valor_venta',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='valor de la venta'),
        ),
    ]
