# Generated by Django 2.2.5 on 2019-09-23 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20190923_0019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='ciuda',
            new_name='ciudad',
        ),
    ]
