# Generated by Django 2.2.5 on 2019-10-11 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bodega', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadmedida',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidadmedida_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AddField(
            model_name='unidadmedida',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidadmedida_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='modificado por'),
        ),
        migrations.AddField(
            model_name='productodetallado',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productodetallado_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AddField(
            model_name='productodetallado',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productodetallado_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='modificado por'),
        ),
        migrations.AddField(
            model_name='productodetallado',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producto_detallado_producto', to='bodega.Producto', verbose_name='producto'),
        ),
        migrations.AddField(
            model_name='productodetallado',
            name='unidad_medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producto_detallado_unidad_medida', to='bodega.UnidadMedida', verbose_name='unidad de medida'),
        ),
        migrations.AddField(
            model_name='producto',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AddField(
            model_name='producto',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='modificado por'),
        ),
        migrations.AddField(
            model_name='produccionproducto',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produccionproducto_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AddField(
            model_name='produccionproducto',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produccionproducto_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='modificado por'),
        ),
        migrations.AddField(
            model_name='produccionproducto',
            name='producto_detallado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produccion_producto_producto_detallado', to='bodega.ProductoDetallado', verbose_name='producto'),
        ),
        migrations.AddField(
            model_name='marca',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marca_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AddField(
            model_name='marca',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marca_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='modificado por'),
        ),
        migrations.AddField(
            model_name='insumodetallado',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insumodetallado_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AddField(
            model_name='insumodetallado',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insumo_detallado_insumo', to='bodega.Insumo', verbose_name='insumo'),
        ),
        migrations.AddField(
            model_name='insumodetallado',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bodega.Marca', verbose_name='marca'),
        ),
        migrations.AddField(
            model_name='insumodetallado',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insumodetallado_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='modificado por'),
        ),
        migrations.AddField(
            model_name='insumodetallado',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insumo_detallado_unidad_medida', to='bodega.UnidadMedida', verbose_name='unidad de medida'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insumo_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insumo_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='modificado por'),
        ),
        migrations.AddField(
            model_name='comprainsumo',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comprainsumo_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AddField(
            model_name='comprainsumo',
            name='insumo_detallado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compra_insumo_insumo_detallado', to='bodega.InsumoDetallado', verbose_name='insumo detallado'),
        ),
        migrations.AddField(
            model_name='comprainsumo',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comprainsumo_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='modificado por'),
        ),
    ]
