# Generated by Django 2.2.5 on 2019-10-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0002_auto_20191011_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprainsumo',
            name='precio_unitario',
            field=models.PositiveIntegerField(verbose_name='precio unitario'),
        ),
        migrations.AlterField(
            model_name='comprainsumo',
            name='unidades',
            field=models.PositiveIntegerField(verbose_name='unidades'),
        ),
        migrations.AlterField(
            model_name='comprainsumo',
            name='valor_compra',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='valor de la compra'),
        ),
        migrations.AlterField(
            model_name='insumodetallado',
            name='cantidad',
            field=models.PositiveIntegerField(verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='produccionproducto',
            name='precio_costo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='precio de costo'),
        ),
        migrations.AlterField(
            model_name='produccionproducto',
            name='unidades_producidas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='unidades producidas'),
        ),
        migrations.AlterField(
            model_name='productodetallado',
            name='cantidad',
            field=models.PositiveIntegerField(verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='productodetallado',
            name='precio_venta',
            field=models.PositiveIntegerField(verbose_name='precio de venta'),
        ),
        migrations.AlterField(
            model_name='productodetallado',
            name='unidades_disponibles',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='unidades disponibles'),
        ),
    ]
