# Generated by Django 2.2.5 on 2019-10-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0002_auto_20191017_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccionproducto',
            name='lote_agotado',
            field=models.BooleanField(default=False, verbose_name='lote agotado'),
        ),
        migrations.AddField(
            model_name='produccionproducto',
            name='unidades_vencidas',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='unidades vencidas'),
        ),
        migrations.AddField(
            model_name='produccionproducto',
            name='unidades_vendidas',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='unidades vendidas'),
        ),
    ]
